name: Build and Sign

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.0

    - name: Build with PyInstaller
      uses: sayyid5416/pyinstaller@v1
      with:
        spec: main.py
        requirements: requirements.txt
        options: --onefile, --noconsole

    - name: Code sign a file
      uses: dlemstra/code-sign-action@v1
      with:
        certificate: '${{ secrets.SIGNING_KEY }}'
        password: '${{ secrets.CERT_PASSWORD }}'
        files:
          './dist/main.exe'

    - name: Rename Artifact
      run: mv ./dist/main.exe ./dist/ScryptTunes.exe

    - name: Create Release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "./dist/ScryptTunes.exe"

